function ok = CheckVectorOk(vector, n)
% CHECKVECTOROK Verifier les suites de trois valeurs et les nombres de zeros et de uns.
% Une case vide est representee par NaN, qui ne vaut jamais un autre NaN.
% Implementation avec assistance de Codex, 2026.
ok = isnumeric(n) && isreal(n) && isscalar(n) && isfinite(n) && ...
    n >= 2 && n == fix(n) && mod(n, 2) == 0 && ...
    isa(vector, 'double') && isreal(vector) && isvector(vector) && ...
    numel(vector) == n;
if ~ok
    return
end
v = vector(:).';
ok = all(isnan(v) | v == 0 | v == 1) && ...
    sum(v == 0) <= n / 2 && sum(v == 1) <= n / 2 && ...
    ~any(v(1:end-2) == v(2:end-1) & v(2:end-1) == v(3:end));
end
