function fig = CreateBinairoFigure(Original, Solution, file, feasible)
% CREATEBINAIROFIGURE Draw a hidden, inspectable figure for DisplayBinairo.
% Style source: MATLAB 1 p1; P00 2026.2 p32; supplied example PDFs p1.
% AI-assisted team implementation, 2026. Human attribution: project report.
% This function returns its figure for native style tests. Caller closes it.
if ~BinairoShapeOK(Original) || ~BinairoShapeOK(Solution) || ...
        ~isequal(size(Original), size(Solution))
    error('Binairo:DisplayGrid', 'Original and Solution must be equal even square 0/1/NaN double matrices.');
end
if ~isscalar(feasible) || ~(islogical(feasible) || isnumeric(feasible)) || ...
        ~isreal(feasible) || ~(feasible == 0 || feasible == 1)
    error('Binairo:FeasibleFlag', 'feasible must be a scalar logical or 0/1 value.');
end
[~, sourceName] = BinairoOutputPath(file);
clues = ~isnan(Original);
if feasible && (~BinairoGridValid(Solution) || any(Solution(clues) ~= Original(clues)))
    error('Binairo:DisplaySolution', 'A feasible display must obey the rules and preserve every original clue.');
end
if ~feasible
    Solution = Original; % Never display failed guesses as a proposed answer.
end
n = size(Original, 1);
nameLines = regexp(sourceName, '.{1,32}', 'match');
headerHeight = max(0.9, 0.25 * (numel(nameLines) + 1)) * n / 6;
fig = figure('Visible', 'off', 'Color', 'white', 'Name', 'Binairo result', ...
    'NumberTitle', 'off', 'Position', [100 100 700 820], ...
    'PaperUnits', 'inches', 'PaperSize', [8.5 11], ...
    'PaperPosition', [0.45 1.05 7.6 8.9], 'PaperPositionMode', 'manual');
try
    ax = axes('Parent', fig, 'Position', [0.07 0.07 0.86 0.86], ...
        'XLim', [-0.05 n + 0.05], 'YLim', [-headerHeight n + 0.05], ...
        'YDir', 'reverse', 'DataAspectRatio', [1 1 1], 'Visible', 'off');
    ticks = 0:n;
    line(ax, [ticks; ticks], [zeros(size(ticks)); n * ones(size(ticks))], ...
        'Color', 'black', 'LineWidth', 0.75, 'Tag', 'GridLine');
    line(ax, [zeros(size(ticks)); n * ones(size(ticks))], [ticks; ticks], ...
        'Color', 'black', 'LineWidth', 0.75, 'Tag', 'GridLine');
    [x, y] = meshgrid((1:n) - 0.5, (1:n) - 0.5);
    fontSize = max(8, min(24, 132 / n));
    if any(clues(:))
        text(ax, x(clues), y(clues), cellstr(num2str(Original(clues), '%d')), ...
            'Color', [0 0 0], 'FontWeight', 'bold', 'FontSize', fontSize, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'OriginalDigit');
    end
    filled = isnan(Original) & ~isnan(Solution);
    if any(filled(:))
        text(ax, x(filled), y(filled), cellstr(num2str(Solution(filled), '%d')), ...
            'Color', [0 0 1], 'FontWeight', 'bold', 'FontSize', fontSize, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'SolvedDigit');
    end
    text(ax, 0, -headerHeight + 0.12 * n / 6, nameLines, ...
        'Color', [0 0 1], 'FontWeight', 'bold', 'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
        'Interpreter', 'none', 'Tag', 'SourceFilename');
    stamp = char(datetime('now'), 'dd-MMM-yyyy HH:mm:ss', 'en_US');
    text(ax, n, -headerHeight + 0.12 * n / 6, stamp, ...
        'Color', [0 0 0], 'FontSize', 8, 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', 'Interpreter', 'none', 'Tag', 'CreationTime');
    if ~feasible
        text(ax, n / 2, n / 2, '== Error ==', 'Color', [1 0 0], ...
            'FontWeight', 'bold', 'FontSize', 44, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'ErrorMessage');
    end
    drawnow;
catch exception
    close(fig);
    rethrow(exception);
end
end
