function figureBinairo = CreerFigureBinairo(grilleInitiale, grilleResolue, fichier, faisable)
% CREERFIGUREBINAIRO Construire la figure utilisee par DisplayBinairo ; son appelant la ferme.
% Presentation : exercice MATLAB 1, p. 1 ; P00, p. 32 ; PDF exemples du cours.
% Le texte == Error == est conserve tel que demande par le professeur.
% Implementation avec assistance de Codex, 2026.
if ~FormatGrilleValide(grilleInitiale) || ~FormatGrilleValide(grilleResolue) || ...
        ~isequal(size(grilleInitiale), size(grilleResolue))
    error('Binairo:GrilleAffichage', 'Les grilles doivent etre carrees, de meme taille paire, de type double, avec 0, 1 ou NaN.');
end
if ~isscalar(faisable) || ~(islogical(faisable) || isnumeric(faisable)) || ...
        ~isreal(faisable) || ~(faisable == 0 || faisable == 1)
    error('Binairo:IndicateurFaisabilite', 'La faisabilite doit etre un scalaire logique ou valoir 0 ou 1.');
end
[~, nomSource] = CheminPdfBinairo(fichier);
indicesInitiaux = ~isnan(grilleInitiale);
if faisable && (~GrilleBinairoValide(grilleResolue) || any(grilleResolue(indicesInitiaux) ~= grilleInitiale(indicesInitiaux)))
    error('Binairo:SolutionAffichage', 'Une solution affichee comme faisable doit respecter les regles et les indices initiaux.');
end
if ~faisable
    grilleResolue = grilleInitiale; % En cas d'echec, afficher seulement les indices initiaux.
end
n = size(grilleInitiale, 1);
lignesNom = regexp(nomSource, '.{1,32}', 'match');
hauteurEntete = max(0.9, 0.25 * (numel(lignesNom) + 1)) * n / 6;
figureBinairo = figure('Visible', 'off', 'Color', 'white', 'Name', 'Resultat du Binairo', ...
    'NumberTitle', 'off', 'Position', [100 100 700 820], ...
    'PaperUnits', 'inches', 'PaperSize', [8.5 11], ...
    'PaperPosition', [0.45 1.05 7.6 8.9], 'PaperPositionMode', 'manual');
try
    axesBinairo = axes('Parent', figureBinairo, 'Position', [0.07 0.07 0.86 0.86], ...
        'XLim', [-0.05 n + 0.05], 'YLim', [-hauteurEntete n + 0.05], ...
        'YDir', 'reverse', 'DataAspectRatio', [1 1 1], 'Visible', 'off');
    graduations = 0:n;
    line(axesBinairo, [graduations; graduations], [zeros(size(graduations)); n * ones(size(graduations))], ...
        'Color', 'black', 'LineWidth', 0.75, 'Tag', 'TraitGrille');
    line(axesBinairo, [zeros(size(graduations)); n * ones(size(graduations))], [graduations; graduations], ...
        'Color', 'black', 'LineWidth', 0.75, 'Tag', 'TraitGrille');
    [x, y] = meshgrid((1:n) - 0.5, (1:n) - 0.5);
    taillePolice = max(8, min(24, 132 / n));
    if any(indicesInitiaux(:))
        text(axesBinairo, x(indicesInitiaux), y(indicesInitiaux), cellstr(num2str(grilleInitiale(indicesInitiaux), '%d')), ...
            'Color', [0 0 0], 'FontWeight', 'bold', 'FontSize', taillePolice, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'ChiffreInitial');
    end
    casesResolues = isnan(grilleInitiale) & ~isnan(grilleResolue);
    if any(casesResolues(:))
        text(axesBinairo, x(casesResolues), y(casesResolues), cellstr(num2str(grilleResolue(casesResolues), '%d')), ...
            'Color', [0 0 1], 'FontWeight', 'bold', 'FontSize', taillePolice, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'ChiffreResolu');
    end
    text(axesBinairo, 0, -hauteurEntete + 0.12 * n / 6, lignesNom, ...
        'Color', [0 0 1], 'FontWeight', 'bold', 'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
        'Interpreter', 'none', 'Tag', 'NomFichierSource');
    dateCreation = char(datetime('now'), 'dd.MM.yyyy HH:mm:ss');
    text(axesBinairo, n, -hauteurEntete + 0.12 * n / 6, dateCreation, ...
        'Color', [0 0 0], 'FontSize', 8, 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', 'Interpreter', 'none', 'Tag', 'DateCreation');
    if ~faisable
        text(axesBinairo, n / 2, n / 2, '== Error ==', 'Color', [1 0 0], ...
            'FontWeight', 'bold', 'FontSize', 44, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', 'Tag', 'MessageErreur');
    end
    drawnow;
catch exception
    close(figureBinairo);
    rethrow(exception);
end
end
