function RunBinairo(B, sourceFile, solveWithMatlab, showPDF)
% RUNBINAIRO Entry point for the solve.m script GENERATED BY LABVIEW.
% Contract: docs/INTERFACE_CONTRACT.md. No image processing occurs in MATLAB.
% AI-assisted team implementation, 2026. Human attribution: project report.
% This entry point owns MatlabRun.log/MatlabStatus.txt/MatlabError.txt here.
% It closes an existing diary: run one pipeline at a time in each directory.
runtimeDir = fileparts(mfilename('fullpath'));
statusPath = fullfile(runtimeDir, 'MatlabStatus.txt');
errorPath = fullfile(runtimeDir, 'MatlabError.txt');
logPath = fullfile(runtimeDir, 'MatlabRun.log');
diary('off');
try
    DeleteOld(statusPath);
    DeleteOld(errorPath);
    DeleteOld(logPath);
    diary(logPath);
    closeDiary = onCleanup(@() diary('off')); %#ok<NASGU>
    fprintf('Binairo MATLAB run started %s\n', char(datetime('now')));
    fprintf('MATLAB %s | %s\n', version, computer);
    [pdfPath, sourceName] = BinairoOutputPath(sourceFile);
    DeleteOld(pdfPath);
    fprintf('Source: %s\n', sourceName);
    if ~islogical(solveWithMatlab) || ~isscalar(solveWithMatlab) || ...
            ~islogical(showPDF) || ~isscalar(showPDF)
        error('Binairo:Options', 'solveWithMatlab and showPDF must be scalar logicals.');
    end
    if ~BinairoShapeOK(B)
        error('Binairo:InputGrid', 'B must be an even square real double matrix of 0, 1, and NaN, with n >= 2.');
    end
    fprintf('Grid: %d x %d; solve=%d; showPDF=%d\n', size(B, 1), size(B, 2), solveWithMatlab, showPDF);
    printGrid(B);
    if solveWithMatlab
        [solution, feasible] = SolveBinairo(B);
    else
        solution = B;
        feasible = BinairoGridValid(B);
        fprintf('Solving disabled: rendering only the original clues.\n');
    end
    DisplayBinairo(B, solution, sourceFile, feasible);
    if showPDF
        browserStatus = web(pdfPath, '-browser');
        if browserStatus ~= 0
            error('Binairo:PDFViewer', 'PDF saved, but the system PDF browser could not start (status %d).', browserStatus);
        end
        fprintf('Requested the system browser to open the PDF.\n');
    end
    if feasible
        result = 'OK';
    else
        result = 'UNSOLVABLE';
    end
    BinairoWriteText(statusPath, [result char(10)]);
    fprintf('BINAIRO STATUS: %s\n', result);
catch exception
    report = getReport(exception, 'extended', 'hyperlinks', 'off');
    fprintf(2, '%s\n', report);
    % Reporting failure must not replace the original exception in MATLAB.
    try
        BinairoWriteText(errorPath, [report char(10)]);
        BinairoWriteText(statusPath, ['ERROR' char(10)]);
    catch reportException
        fprintf(2, 'Could not write error/status files: %s\n', reportException.message);
    end
    rethrow(exception);
end
end

function DeleteOld(file)
if exist(file, 'file') == 2
    delete(file);
end
end
